-- Media storage has moved out of Supabase Storage.
--
-- App data still lives in the main Supabase project, while images/media are
-- uploaded to Cloudflare R2 through:
--
--   backend/supabase/functions/media-upload
--
-- Configure these Edge Function secrets before deploying the function:
--
--   CLOUDFLARE_R2_ACCOUNT_ID
--   CLOUDFLARE_R2_ACCESS_KEY_ID
--   CLOUDFLARE_R2_SECRET_ACCESS_KEY
--   CLOUDFLARE_R2_BUCKET
--   CLOUDFLARE_R2_PUBLIC_BASE_URL
--
-- Optional:
--
--   CLOUDFLARE_R2_REGION=auto
--   CLOUDFLARE_R2_MAX_UPLOAD_BYTES=8388608
--
-- The database stores public Cloudflare URLs in existing text/json fields such
-- as user_account.avatar and forum_post_media.url, so no Supabase Storage
-- bucket or storage.objects policy is needed.
