"""
Generate place tags for Hello Vietnam.

This script uses 3 sources:
1. Subcategory default tags:
   place_subcategory.default_tag_codes

2. Attribute rule tags:
   estimated_duration_minutes, minimum_price, maximum_price

3. Embedding tags:
   name + description + subcategory text
   compared with tag.description

Important:
- Service places are skipped by is_itinerary_eligible = false.
- Main tags are not generated by embedding.
- Attribute tags are not generated by embedding.
- Service tags are not generated by embedding.

Requirements (NOT in main requirements.txt — install separately):
  pip install sentence-transformers

Run from cf_service/ root:
  python scripts/generate_place_tags.py
"""

from __future__ import annotations

import sys
from typing import Any

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from db.supabase_client import get_supabase_client


MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

BATCH_SIZE = 500
TOP_K_EMBEDDING_TAGS = 4
SIMILARITY_THRESHOLD = 0.38

SOURCE_SUBCATEGORY = "subcategory_rule"
SOURCE_ATTRIBUTE = "attribute_rule"
SOURCE_EMBEDDING = "auto_embedding"

GENERATED_SOURCES = [
    SOURCE_SUBCATEGORY,
    SOURCE_ATTRIBUTE,
    SOURCE_EMBEDDING,
]


if hasattr(sys.stdout, "reconfigure"):
    # Avoid Windows console encoding errors when printing Vietnamese place names.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def fetch_tags(supabase: Any) -> list[dict]:
    response = (
        supabase
        .table("tag")
        .select(
            """
            id_tag,
            tag_code,
            tag_name,
            description,
            tag_group,
            is_active,
            is_user_selectable,
            use_for_auto_tagging
            """
        )
        .eq("is_active", True)
        .execute()
    )
    return response.data or []


def build_tag_map(tags: list[dict]) -> dict[str, dict]:
    return {
        tag["tag_code"]: tag
        for tag in tags
        if tag.get("tag_code")
    }


def get_embedding_candidate_tags(tags: list[dict]) -> list[dict]:
    candidate_tags = []
    for tag in tags:
        if tag.get("use_for_auto_tagging") is not True:
            continue
        if tag.get("tag_group") in {"main", "attribute", "service"}:
            continue
        if not tag.get("description"):
            continue
        candidate_tags.append(tag)
    return candidate_tags


def fetch_places_batch(
    supabase: Any,
    offset: int,
    batch_size: int = BATCH_SIZE,
) -> list[dict]:
    start = offset
    end = offset + batch_size - 1

    response = (
        supabase
        .table("place")
        .select(
            """
            id_place,
            name,
            short_description,
            detailed_description,
            status,
            minimum_price,
            maximum_price,
            estimated_duration_minutes,
            id_place_subcategory,
            place_subcategory (
                id_place_subcategory,
                name,
                place_category,
                is_itinerary_eligible,
                default_tag_codes
            )
            """
        )
        .eq("status", "active")
        .range(start, end)
        .execute()
    )
    return response.data or []


def normalize_default_tag_codes(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if item and str(item).strip()]


def is_itinerary_eligible(place: dict) -> bool:
    subcategory = place.get("place_subcategory") or {}
    return subcategory.get("is_itinerary_eligible") is True


def build_place_text(place: dict) -> str:
    subcategory = place.get("place_subcategory") or {}
    parts = [
        place.get("name") or "",
        subcategory.get("name") or "",
        subcategory.get("place_category") or "",
        place.get("short_description") or "",
        place.get("detailed_description") or "",
    ]
    return ". ".join(part.strip() for part in parts if part and part.strip())


def build_tag_text(tag: dict) -> str:
    parts = [
        tag.get("tag_code") or "",
        tag.get("tag_name") or "",
        tag.get("description") or "",
    ]
    return ". ".join(part.strip() for part in parts if part and part.strip())


def get_default_tags_from_subcategory(place: dict) -> list[str]:
    subcategory = place.get("place_subcategory") or {}
    return normalize_default_tag_codes(subcategory.get("default_tag_codes"))


def get_attribute_tags(place: dict) -> list[str]:
    tags = []
    duration = place.get("estimated_duration_minutes")
    if duration is not None:
        try:
            duration = int(duration)
            if duration <= 60:
                tags.append("quick_visit")
            elif duration >= 150:
                tags.append("long_visit")
        except (TypeError, ValueError):
            pass
    max_price = place.get("maximum_price")
    if max_price is not None:
        try:
            max_price = float(max_price)
            if max_price <= 200_000:
                tags.append("budget_friendly")
            elif max_price >= 1_000_000:
                tags.append("premium")
        except (TypeError, ValueError):
            pass
    return tags


def generate_embedding_tags_for_place(
    place_embedding,
    candidate_tags: list[dict],
    tag_embeddings,
) -> list[tuple[str, float]]:
    similarities = cosine_similarity([place_embedding], tag_embeddings)[0]
    scored_tags = []
    for tag, score in zip(candidate_tags, similarities):
        score = float(score)
        if score >= SIMILARITY_THRESHOLD:
            scored_tags.append((tag["tag_code"], round(score, 4)))
    scored_tags.sort(key=lambda item: item[1], reverse=True)
    return scored_tags[:TOP_K_EMBEDDING_TAGS]


def add_tag(tag_scores: dict[str, dict], tag_code: str, confidence_score: float, source: str) -> None:
    if not tag_code:
        return
    existing = tag_scores.get(tag_code)
    if existing is None:
        tag_scores[tag_code] = {"confidence_score": round(float(confidence_score), 4), "source": source}
        return
    if confidence_score > existing["confidence_score"]:
        tag_scores[tag_code] = {"confidence_score": round(float(confidence_score), 4), "source": source}


def resolve_conflicts(tag_scores: dict[str, dict]) -> dict[str, dict]:
    mutually_exclusive_pairs = [
        ("quick_visit", "long_visit"),
        ("budget_friendly", "premium"),
        ("quiet", "crowded"),
    ]
    for tag_a, tag_b in mutually_exclusive_pairs:
        if tag_a not in tag_scores or tag_b not in tag_scores:
            continue
        score_a = tag_scores[tag_a]["confidence_score"]
        score_b = tag_scores[tag_b]["confidence_score"]
        if abs(score_a - score_b) < 0.05:
            tag_scores.pop(tag_a, None)
            tag_scores.pop(tag_b, None)
            continue
        if score_a >= score_b:
            tag_scores.pop(tag_b, None)
        else:
            tag_scores.pop(tag_a, None)
    return tag_scores


def build_place_tags(place: dict, tag_map: dict[str, dict], embedding_tags: list[tuple[str, float]]) -> dict[str, dict]:
    tag_scores: dict[str, dict] = {}
    for tag_code in get_default_tags_from_subcategory(place):
        if tag_code in tag_map:
            add_tag(tag_scores, tag_code, 1.0, SOURCE_SUBCATEGORY)
    for tag_code in get_attribute_tags(place):
        if tag_code in tag_map:
            add_tag(tag_scores, tag_code, 1.0, SOURCE_ATTRIBUTE)
    for tag_code, score in embedding_tags:
        if tag_code in tag_map:
            add_tag(tag_scores, tag_code, score, SOURCE_EMBEDDING)
    return resolve_conflicts(tag_scores)


def delete_old_generated_tags(supabase: Any, place_id: str) -> None:
    for source in GENERATED_SOURCES:
        supabase.table("place_tag").delete().eq("id_place", place_id).eq("source", source).execute()


def fetch_protected_tag_ids(supabase: Any, place_id: str) -> set[str]:
    response = supabase.table("place_tag").select("id_tag, source").eq("id_place", place_id).execute()
    rows = response.data or []
    return {row["id_tag"] for row in rows if row.get("source") not in GENERATED_SOURCES}


def insert_place_tags(supabase: Any, place_id: str, tag_scores: dict[str, dict], tag_map: dict[str, dict], protected_tag_ids: set[str]) -> int:
    rows = []
    for tag_code, info in tag_scores.items():
        tag = tag_map.get(tag_code)
        if not tag:
            continue
        id_tag = tag["id_tag"]
        if id_tag in protected_tag_ids:
            continue
        rows.append({
            "id_place": place_id,
            "id_tag": id_tag,
            "confidence_score": info["confidence_score"],
            "source": info["source"],
        })
    if not rows:
        return 0
    supabase.table("place_tag").insert(rows).execute()
    return len(rows)


def print_place_result(place: dict, tag_scores: dict[str, dict], inserted_count: int) -> None:
    subcategory = place.get("place_subcategory") or {}
    print("-" * 80)
    print(f"Place: {place.get('name')}")
    print(f"Subcategory: {subcategory.get('name')}")
    print(f"Inserted tags: {inserted_count}")
    if not tag_scores:
        print("Generated tags: none")
        return
    for tag_code, info in sorted(tag_scores.items(), key=lambda item: item[1]["confidence_score"], reverse=True):
        print(f"  {tag_code} score={info['confidence_score']} source={info['source']}")


def process_place(supabase, place, place_embedding, candidate_tags, tag_embeddings, tag_map) -> int:
    embedding_tags = generate_embedding_tags_for_place(place_embedding, candidate_tags, tag_embeddings)
    tag_scores = build_place_tags(place, tag_map, embedding_tags)
    delete_old_generated_tags(supabase, place["id_place"])
    protected_tag_ids = fetch_protected_tag_ids(supabase, place["id_place"])
    inserted_count = insert_place_tags(supabase, place["id_place"], tag_scores, tag_map, protected_tag_ids)
    print_place_result(place, tag_scores, inserted_count)
    return inserted_count


def main():
    supabase = get_supabase_client()

    print("Fetching active tags...")
    tags = fetch_tags(supabase)
    if not tags:
        raise ValueError("No active tags found in public.tag")

    tag_map = build_tag_map(tags)
    candidate_tags = get_embedding_candidate_tags(tags)
    if not candidate_tags:
        raise ValueError("No embedding candidate tags found. Check tag.use_for_auto_tagging and tag_group.")

    print(f"Total active tags: {len(tags)}")
    print(f"Embedding candidate tags: {len(candidate_tags)}")
    print(f"Batch size: {BATCH_SIZE}")

    print("Loading embedding model...")
    model = SentenceTransformer(MODEL_NAME)
    tag_texts = [build_tag_text(tag) for tag in candidate_tags]

    print("Encoding tag texts...")
    tag_embeddings = model.encode(tag_texts, normalize_embeddings=True, show_progress_bar=True)

    total_fetched = 0
    total_eligible = 0
    total_skipped = 0
    total_inserted = 0
    offset = 0
    batch_index = 1

    while True:
        print("=" * 80)
        print(f"Fetching batch {batch_index} | offset={offset}")

        places = fetch_places_batch(supabase, offset)
        if not places:
            print("No more places. Stop.")
            break

        total_fetched += len(places)
        eligible_places = [p for p in places if is_itinerary_eligible(p)]
        skipped_places  = [p for p in places if not is_itinerary_eligible(p)]
        total_eligible += len(eligible_places)
        total_skipped  += len(skipped_places)

        print(f"Fetched in batch: {len(places)}")
        print(f"Eligible in batch: {len(eligible_places)}")
        print(f"Skipped in batch: {len(skipped_places)}")

        if eligible_places:
            place_texts = [build_place_text(place) for place in eligible_places]
            print("Encoding place texts...")
            place_embeddings = model.encode(place_texts, normalize_embeddings=True, show_progress_bar=True)
            for place, place_embedding in zip(eligible_places, place_embeddings):
                total_inserted += process_place(supabase, place, place_embedding, candidate_tags, tag_embeddings, tag_map)

        offset += BATCH_SIZE
        batch_index += 1

    print("=" * 80)
    print("Finished full run.")
    print(f"Total fetched places: {total_fetched}")
    print(f"Total eligible places: {total_eligible}")
    print(f"Total skipped places: {total_skipped}")
    print(f"Total inserted place_tag rows: {total_inserted}")


if __name__ == "__main__":
    main()
