[functions.location-preference]
enabled = true
verify_jwt = true
entrypoint = "./functions/users/location-preference/index.ts"
import_map = "./functions/users/location-preference/deno.json"

[functions.travel-preferences]
enabled = true
verify_jwt = true
entrypoint = "./functions/users/travel-preferences/index.ts"
import_map = "./functions/users/travel-preferences/deno.json"
